name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VPS_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519

      - name: Pull Docker image from GHCR
        env:
          GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'
          echo "$GHCR_TOKEN" | docker login ghcr.io -u USERNAME --password-stdin
          docker pull ghcr.io/OWNER/REPOSITORY:TAG
          docker stop CONTAINER_NAME || true
          docker rm CONTAINER_NAME || true
          docker run -d --name CONTAINER_NAME -p 80:80 ghcr.io/OWNER/REPOSITORY:TAG
          EOF
